[package]
name = "ascii_map_maker"
version = "0.1.0"
authors = ["Rens Althuis <Rens.Althuis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "^1.5.5"
byteorder = "^1.3.4"
utf8-decode = "^1.0.0"